### ISSUE TITLE
EndeavourOS does not boot after installing apparmor.d-git

### ISSUE THREAD

**Issue by PhysicsIsAwesome** [roddhjav/apparmor.d#296]
EndeavourOS does not boot anymore after installing apparmor.d-git, both in enforcing mode and also in audit mode. I could not figure out the exact problem, but it seems like a step in the boot process failed to mount needed partitions. Only solution I found was to uninstall apparmor.d-git via arch-chroot from a live ISO.

Configuration:
- apparmor.d-git 0.1633-1
- EndeavourOS (Arch)
- Kernels: linux-hardened 6.7.3.hardened1-3 and linux 6.7.4.arch1-1
- BTRFS EndeavourOS default partitioning
- systemd-boot with UKI and secure boot

**Comment by roddhjav** [comment]
Can you collect the apparmor log from this issue and post it here? https://apparmor.pujol.io/report/ 

The recovery solution in case of such an issue is detailled here: https://apparmor.pujol.io/recovery/

**Comment by PhysicsIsAwesome** [comment]
```
apparmor="DENIED" operation="capable" class="cap" profile="zgrep"  comm="zgrep" capability=2  capname="dac_read_search"
apparmor="DENIED" operation="capable" class="cap" profile="zgrep"  comm="zgrep" capability=1  capname="dac_override"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-generator-gpt-auto" name="@{sys}/firmware/efi/efivars/LoaderDevicePartUUID-@{uuid}"  comm="systemd-gpt-aut" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="create" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="netlink" sock_type="raw" protocol=0 requested_mask="create" denied_mask="create"
apparmor="ALLOWED" operation="bind" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="netlink" sock_type="raw" protocol=0 requested_mask="bind" denied_mask="bind"
apparmor="ALLOWED" operation="getsockname" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="netlink" sock_type="raw" protocol=0 requested_mask="getattr" denied_mask="getattr"
apparmor="ALLOWED" operation="sendmsg" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="netlink" sock_type="raw" protocol=0 requested_mask="send" denied_mask="send"
apparmor="ALLOWED" operation="recvmsg" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="netlink" sock_type="raw" protocol=0 requested_mask="receive" denied_mask="receive"
apparmor="ALLOWED" operation="create" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create"
apparmor="ALLOWED" operation="connect" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet" sock_type="dgram" protocol=17 requested_mask="connect" denied_mask="connect"
apparmor="ALLOWED" operation="getsockname" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" laddr=127.0.0.1 lport=57603 faddr=127.0.0.1 fport=6001 family="inet" sock_type="dgram" protocol=17 requested_mask="getattr" denied_mask="getattr"
apparmor="ALLOWED" operation="create" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet6" sock_type="dgram" protocol=0 requested_mask="create" denied_mask="create"
apparmor="ALLOWED" operation="create" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
apparmor="ALLOWED" operation="setsockopt" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet" sock_type="stream" protocol=6 requested_mask="setopt" denied_mask="setopt"
apparmor="ALLOWED" operation="connect" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet" sock_type="stream" protocol=6 requested_mask="connect" denied_mask="connect"
apparmor="ALLOWED" operation="create" class="net" profile="polkit-kde-authentication-agent"  comm="polkit-kde-auth" family="inet6" sock_type="stream" protocol=6 requested_mask="create" denied_mask="create"
apparmor="ALLOWED" operation="capable" class="cap" info="optional: no audit" error=-1 profile="aa-log"  comm="journalctl" capability=27  capname="mknod"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0800:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0800:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C04:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C04:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C09:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/ACPI0003:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:ACPI0003:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/LEN0100:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:LEN0100:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/LEN0111:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:LEN0111:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/LEN0130:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:LEN0130:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/LEN0268:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:LEN0268:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/PNP0C0A:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C0A:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/ACPI0007:0c/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:ACPI0007:0c"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/ACPI0007:0d/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:ACPI0007:0d"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/ACPI0007:0e/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:ACPI0007:0e"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/ACPI0007:0f/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:ACPI0007:0f"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/AMDI0005:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:AMDI0005:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/AMDI0010:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:AMDI0010:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/AMDI0010:01/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:AMDI0010:01"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/AMDI0030:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:AMDI0030:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/DRTM0001:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:DRTM0001:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/NTC0702:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:NTC0702:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C0C:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C0C:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C0D:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C0D:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C0E:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C0E:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:01/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:01"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:02/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:02"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:03/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:03"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:04/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:04"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/PNP0C14:05/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:PNP0C14:05"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/USBC000:00/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:USBC000:00"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/acpi-cpufreq/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:acpi-cpufreq"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/efivars.0/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:efivars.0"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/i8042/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:i8042"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/intel_rapl_msr.0/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:intel_rapl_msr.0"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/microcode/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:microcode"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/pcspkr/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:pcspkr"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/reg-dummy/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:reg-dummy"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/regulatory.0/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:regulatory.0"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/rtc-efi.0/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:rtc-efi.0"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/serial8250/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:serial8250"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/snd-soc-dummy/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:snd-soc-dummy"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/sp5100-tco/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:sp5100-tco"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/thinkpad_acpi/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:thinkpad_acpi"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/thinkpad_hwmon/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:thinkpad_hwmon"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/pnp0/00:01/rtc/rtc0/alarmtimer.0.auto/uevent"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{run}/udev/data/+platform:alarmtimer.0.auto"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="power-profiles-daemon" name="@{sys}/devices/platform/thinkpad_acpi/dytc_lapmode"  comm="power-profiles-" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="capable" class="cap" info="optional: no audit" error=-1 profile="xorg"  comm="Xorg" capability=27  capname="mknod"
apparmor="ALLOWED" operation="capable" class="cap" info="optional: no audit" error=-1 profile="ps"  comm="ps" capability=27  capname="mknod"
apparmor="ALLOWED" operation="capable" class="cap" info="optional: no audit" error=-1 profile="sysctl"  comm="sysctl" capability=27  capname="mknod"
apparmor="ALLOWED" operation="open" class="file" profile="xorg" name="@{run}/udev/data/+sound:card0"  comm="Xorg" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="xorg" name="@{run}/udev/data/+sound:card1"  comm="Xorg" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="xorg" name="/dev/input/mouse0"  comm="Xorg" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="xorg" name="/dev/input/mouse1"  comm="Xorg" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="xorg" name="/dev/input/mouse2"  comm="Xorg" requested_mask="wr" denied_mask="wr" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:8"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:6"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:7"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:5"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:9"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="systemd-logind" name="@{run}/udev/data/c89:*"  comm="systemd-logind" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="sddm-greeter" name="/usr/share/endeavouros/backgrounds/endeavouros-wallpaper.png"  comm="sddm-greeter" requested_mask="r" denied_mask="r" fsuid=964 ouid=0 FSUID="sddm" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="polkit-kde-authentication-agent" name="/usr/share/libdrm/amdgpu.ids"  comm="polkit-kde-auth" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore"  comm="kded5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore"  comm="kded5" requested_mask="wrc" denied_mask="wrc" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="mknod" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.lock"  comm="kded5" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.lock"  comm="kded5" requested_mask="wrc" denied_mask="wrc" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="file_lock" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.lock"  comm="kded5" requested_mask="wk" denied_mask="wk" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/#@{int}"  comm="kded5" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="chmod" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/#@{int}"  comm="kded5" requested_mask="w" denied_mask="w" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="link" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.UqOgtT"  comm="kded5" requested_mask="l" denied_mask="l" fsuid=1000 ouid=1000 target="@{user_cache_dirs}/plasmashell/hsts/#@{int}" FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="rename_src" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.UqOgtT"  comm="kded5" requested_mask="wrd" denied_mask="wrd" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="rename_dest" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore"  comm="kded5" requested_mask="wc" denied_mask="wc" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="unlink" class="file" profile="kded5" name="@{user_cache_dirs}/plasmashell/hsts/hstsstore.lock"  comm="kded5" requested_mask="d" denied_mask="d" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="/etc/ssl/openssl.cnf"  comm="kded5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kded5" name="/etc/ssl/certs/"  comm="kded5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-chargethresholdhelper" name="@{sys}/devices/@{pci_bus}/0000:00:*.3/PNP0C09:00/ACPI0003:00/power_supply/AC/type"  comm="chargethreshold" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-chargethresholdhelper" name="@{sys}/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2d/PNP0C09:00/PNP0C0A:00/power_supply/BAT0/type"  comm="chargethreshold" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-chargethresholdhelper" name="@{sys}/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2d/PNP0C09:00/PNP0C0A:00/power_supply/BAT0/charge_control_start_threshold"  comm="chargethreshold" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-backlighthelper" name="@{sys}/devices/@{pci_bus}/0000:00:08.1/0000:07:00.0/drm/card1/card1-eDP-1/amdgpu_bl1/type"  comm="backlighthelper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-backlighthelper" name="@{sys}/devices/@{pci_bus}/0000:00:08.1/0000:07:00.0/drm/card1/card1-eDP-1/enabled"  comm="backlighthelper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-backlighthelper" name="@{sys}/devices/@{pci_bus}/0000:00:08.1/0000:07:00.0/drm/card1/card1-eDP-1/amdgpu_bl1/max_brightness"  comm="backlighthelper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-chargethresholdhelper" name="@{sys}/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:2d/PNP0C09:00/PNP0C0A:00/power_supply/BAT0/charge_control_end_threshold"  comm="chargethreshold" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kauth-backlighthelper" name="@{sys}/devices/@{pci_bus}/0000:00:08.1/0000:07:00.0/drm/card1/card1-eDP-1/amdgpu_bl1/brightness"  comm="backlighthelper" requested_mask="r" denied_mask="r" fsuid=0 ouid=0 FSUID="root" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="kwin_wayland" name="@{user_config_dirs}/session/kwin_saved at previous logout_"  comm="kwin_wayland" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="mkdir" class="file" profile="brave" name="/etc/opt/"  comm="brave" requested_mask="c" denied_mask="c" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="/etc/xdg/kdeglobals"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{user_config_dirs}/kdedefaults/kdeglobals"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{user_config_dirs}/kdeglobals"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{user_config_dirs}/kdedefaults/kwinrc"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{user_config_dirs}/kwinrc"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{sys}/devices/virtual/tty/tty0/active"  comm="brave" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="/dev/disk/by-uuid/"  comm="ThreadPoolForeg" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="brave" name="@{user_cache_dirs}/icon-cache.kcache"  comm="brave" requested_mask="wrc" denied_mask="wrc" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="exec" class="file" profile="xdg-settings" name="@{bin}/realpath"  comm="xdg-settings" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0 target="xdg-settings//null-@{bin}/realpath" FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="file_mmap" class="file" profile="xdg-settings//null-@{bin}/realpath" name="@{bin}/realpath"  comm="realpath" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0 FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="exec" class="file" info="profile transition not found" error=-13 profile="xdg-mime" name="@{bin}/ktraderclient5"  comm="xdg-mime" requested_mask="x" denied_mask="x" fsuid=1000 ouid=0 target="@{bin}/ktraderclient5" FSUID="admin" OUID="root"
apparmor="ALLOWED" operation="open" class="file" profile="aa-log" name="@{HOME}/"  comm="aa-log" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
apparmor="ALLOWED" operation="file_receive" class="file" profile="kwin_wayland" name="/dev/shm/.org.chromium.Chromium.TIBv4N"  comm="kwin_wayland" requested_mask="wr" denied_mask="wr" fsuid=1000 ouid=1000 FSUID="admin" OUID="admin"
```

**Comment by roddhjav** [comment]
Thanks for these logs. I have fixed the profiles accordingly. However, I highly doubt that the profiles in here are the ones that broke your setup. There is nothing about mount.

**Comment by PhysicsIsAwesome** [comment]
> I have fixed the profiles accordingly

Thank you

> However, I highly doubt that the profiles in here are the ones that broke your setup.

There were two things which solved the problem:
- running `pacman -R apparmor.d-git` from a live environment
- temporary solution: manually running `mount -a` in the emergency console during failed start. Not sure if this completely solved it or just allowed to boot into the OS.

To my surprise disabling Apparmor globally through removing it from the bootparameters did not solve the issue.

The issue is definitely related to the apparmor.d-git package. There was no other change in the system and I tried installing and uninstalling the package several times, every time with the same result.

**Comment by PhysicsIsAwesome** [comment]
Just tried to install it on a newer version and it works again, both in enforce and complain mode. Same system, no settings changed.

Versions:
- Linux 6.7.9-hardened1-1-hardened x86_64
- apparmor.d-git 0.2126-1
