### ISSUE TITLE
Multiple GPG Agent lead to broken signing

### ISSUE THREAD

**Issue by Stoppedpuma** [roddhjav/apparmor.d#404]
Not sure which profile causes this as setting gpg* to complain doesn't fix this. I encountered this with lazygit and was unable to commit until a teardown. Logs don't show anything, just this from journalctl:

gpg-agent[58120]: command 'PKSIGN' failed: No pinentry
gpg-agent[58120]: failed to read the secret key
gpg-agent[58120]: failed to unprotect the secret key: No pinentry
gpg-agent[58120]: can't connect to the PIN entry module '/usr/bin/pinentry': End of file
gpg-agent[58120]: SIGHUP received - re-reading configuration and flushing cache

**Comment by roddhjav** [comment]
That is a tricky one.

To sum up the issue, 
- Upon need, GPG start a new gpg-agent daemon to handle keyring for each keyring (`~/.gnupg`, `/etc/apt/trusted.gpg.d/`, `/etc/pacman.d/gnupg/`, any other user keyring you have).
- The default gpg-agent has access to most keyrings (ideally it should be limited to only the user's one (so `~/.gnupg`). So the first time you use gpg, it should be ok.
- Other agent can be started with different keyring under a different profile (eg: `pacman//gpg`)
- Sometime a program (in this example, lazygit) can use a gpg-agent that run under a profile that prevent access to the actual needed keyring. 
- It is a pain to debug

I currently don't know how to fix this in a correct way.

**Comment by roddhjav** [comment]
This should now be fixed.

**Comment by Stoppedpuma** [comment]
Still seems to fail, GPG gives this output:

error: gpg failed to sign the data:
[GNUPG:] KEY_CONSIDERED (hidden)
[GNUPG:] BEGIN_SIGNING (hidden)
gpg: signing failed: No pinentry
[GNUPG:] FAILURE sign (hidden)
gpg: signing failed: No pinentry

fatal: failed to write commit object

**Comment by roddhjav** [comment]
You may need to kill any `gpg-agent` and `scdaemon` and try it again.

**Comment by Stoppedpuma** [comment]
This issue still persists after a reboot, aa-log doesn't seem to have logs for either gpg or scdaemon.

**Comment by roddhjav** [comment]
Does it have other logs?

**Comment by roddhjav** [comment]
Please, [share these logs anyway](https://apparmor.pujol.io/report/).

**Comment by Stoppedpuma** [comment]
https://puma.s-ul.eu/axmNfTBt

**Comment by roddhjav** [comment]
They is no gpg in these logs...

Can you provide the output of  `ps auxZ | grep gpg` & `ps auxZ | grep scdaemon` to see how your gpg-agent are confined?

Also, you need to [configure](https://apparmor.pujol.io/configuration/#personal-directories) `@{XDG_PROJECTS_DIR}` to match your `(hidden)` directory.

**Comment by Stoppedpuma** [comment]
> They is no gpg in these logs...

I seem to have misread git as gpg, my apologies!

> Can you provide the output of ps auxZ | grep gpg & ps auxZ | grep scdaemon to see how your gpg-agent are confined?

![image](https://github.com/user-attachments/assets/2d0848ba-0f36-48a4-b118-31aedcd82c10)

> Also, you need to [configure](https://apparmor.pujol.io/configuration/#personal-directories) @{XDG_PROJECTS_DIR} to match your (hidden) directory.

This is already set to that directory.

**Comment by roddhjav** [comment]
Your `ps` means that apparmor is currently disabled...
What distribution/DE are you on?

> This is already set to that directory.

Beware, it is a relative path from `@{HOME}`.

**Comment by Stoppedpuma** [comment]
> Your ps means that apparmor is currently disabled...

Not sure why, aa-status reports correctly and logs are being filled.

> What distribution/DE are you on?

Arch Linux

**Comment by roddhjav** [comment]
> Not sure why, aa-status reports correctly and logs are being filled.

Hum, can you try with `sudo` in front of the `ps`?

**Comment by Stoppedpuma** [comment]
user      1922471  0.0  0.0   7924  5088 pts/5    S+   14:40   0:00 rg gpg
user      1942674  0.0  0.0   7928  5248 pts/5    S+   14:40   0:00 rg scdaemon

**Comment by roddhjav** [comment]
Hum... with `ps auxZ` as I asked before... I have the feeling you don't want me to help you...

**Comment by Stoppedpuma** [comment]
> Hum... with ps auxZ as I asked before... I have the feeling you don't want me to help you...

I don't know where you got this from, if I didn't want help / a fix I wouldn't have opened the issue. That was the output from running with sudo.

> Also, when you run this, please ensure you do have a gpg agent started, and that it does lead to broken signing.

This would probably be why there wasn't anything else as I rebooted sometime between and must've forgot retrying the commit again, retrying after doing that does have more this time.

`sudo auxZ | grep scdaemon`
user         6338  0.0  0.0  83240  5108 ?        SLl  15:37   0:00 scdaemon --multi-server
user         6736  0.0  0.0   7704  5248 pts/1    S+   15:37   0:00 rg scdaemon

`sudo auxZ | grep gpg`
user         6336  0.0  0.0 155796  4856 ?        SLsl 15:37   0:00 /usr/bin/gpg-agent --supervised
user         6790  0.0  0.0   7700  5120 pts/1    S+   15:37   0:00 rg gpg

**Comment by Stoppedpuma** [comment]
it seems that setting gcr-prompter to complain fixes this.

Log is below containing both logs from being enforced and in complain mode. The log is trimmed slightly, only excluding open requests for my user installed fonts similar to `ALLOWED gcr-prompter open owner @{HOME}/.fonts/(fontname) comm=gcr-prompter requested_mask=r denied_mask=r` as that adds an extra 100+ unneccesary lines.

```
DENIED  gcr-prompter open /usr/share/glib-2.0/schemas/gschemas.compiled comm=gcr-prompter requested_mask=r denied_mask=r
DENIED  gcr-prompter open owner @{user_share_dirs}/icons/default/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
DENIED  gcr-prompter open /usr/share/icons/default/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
DENIED  gcr-prompter open /usr/share/X11/xkb/rules/evdev comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/glib-2.0/schemas/gschemas.compiled comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{run}/user/@{uid}/dconf/user comm=gcr-prompter requested_mask=wrc denied_mask=wrc
ALLOWED gcr-prompter open owner @{user_config_dirs}/dconf/user comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/default/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/alias comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/all-scroll comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/default comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/nwse-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/sw-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/se-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/s-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/cell comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/col-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/context-menu comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/copy comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/crosshair comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/e-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/ew-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/nesw-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/move comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/grab comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/grabbing comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/pointer comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/help comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/w-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/n-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/ne-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/no-drop comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/not-allowed comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/ns-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/nw-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/progress comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/row-resize comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/text comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/vertical-text comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/wait comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/zoom-in comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/cursors/zoom-out comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/AdwaitaLegacy/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/hicolor/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/rules/evdev comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/keycodes/evdev comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/keycodes/aliases comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/complete comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/basic comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/pc comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/iso9995 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/extra comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/level5 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/numpad comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/types/mousekeys comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/complete comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/basic comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/ledcaps comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/lednum comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/iso9995 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/mousekeys comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/accessx comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/misc comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/ledscroll comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/xfree86 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/level5 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/compat/caps comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/symbols/pc comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/symbols/srvr_ctrl comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/symbols/keypad comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/symbols/us comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/X11/xkb/symbols/inet comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/gtk-3.0/settings.ini comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_config_dirs}/gtk-3.0/settings.ini comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{HOME}/.themes/Colloid_Black-Dark/gtk-3.0/gtk-dark.css comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/themes/Default/gtk-3.0/gtk-keys.css comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /etc/fonts/fonts.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /etc/fonts/conf.d/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-hinting-slight.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-scale-bitmap-fonts.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-yes-antialias.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/20-unhint-small-vera.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/30-metric-aliases.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/30-win32-aliases.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/40-nonlatin.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/44-source-han-sans-cn.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/44-source-han-sans-hk.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/44-source-han-sans-jp.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/44-source-han-sans-kr.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/44-source-han-sans-tw.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/45-generic.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/45-latin.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/46-noto-mono.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/46-noto-sans.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/46-noto-serif.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/48-spacing.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/49-sansserif.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/50-user.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/51-local.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/60-generic.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/60-latin.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/65-fonts-persian.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/65-nonlatin.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/66-noto-mono.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/66-noto-sans.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/66-noto-serif.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-unifont.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-bookman.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-c059.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-d@{int6}l.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-fallback-backwards.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-fallback-generics.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-fallback-specifics.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-gothic.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-nimbus-mono-ps.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-nimbus-roman.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-nimbus-sans.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-p052.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-standard-symbols-ps.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/69-urw-z003.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/80-delicious.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/90-synthetic.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/99-ttf-readex-pro.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/09-autohint-if-no-hinting.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-autohint.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-hinting-full.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-hinting-medium.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-hinting-none.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-nerd-font-symbols.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-no-antialias.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-sub-pixel-bgr.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-sub-pixel-none.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-sub-pixel-vbgr.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-sub-pixel-vrgb.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/10-unhinted.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/11-lcdfilter-legacy.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/11-lcdfilter-light.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/11-lcdfilter-none.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/25-unhint-nonlatin.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/35-lang-normalize.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/65-khmer.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/70-no-bitmaps-and-emoji.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/70-no-bitmaps-except-emoji.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fontconfig/conf.avail/70-yes-bitmaps.conf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/OTF/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/TTF/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/adobe-source-code-pro/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/adobe-source-han-sans/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/apple-fonts/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/cantarell/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/encodings/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/gnu-free/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/gsfonts/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/noto/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/noto-cjk/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/otf-urbanist/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/ttf-readex-pro/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/encodings/large/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/cache/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_cache_dirs}/fontconfig/@{hex32}-le64.cache-9 comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/fonts/cantarell/Cantarell-VF.otf comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/icon-theme.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/16x16/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/AdwaitaLegacy/icon-theme.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/32x32/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/48x48/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/flatpak/exports/share/icons/hicolor/index.theme comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/hicolor/icon-theme.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/hicolor/icon-theme.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/hicolor/16x16/apps/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/hicolor/32x32/apps/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/hicolor/48x48/apps/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/64x64/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/128x128/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/flatpak/exports/share/icons/hicolor/icon-theme.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/hicolor/256x256/apps/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/256x256/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/Adwaita/512x512/mimetypes/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/icons/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/flatpak/exports/share/icons/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/icons/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/pixmaps/ comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/icons/Adwaita/symbolic/status/dialog-password-symbolic.svg comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open owner @{user_share_dirs}/mime/mime.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /var/lib/flatpak/exports/share/mime/mime.cache comm=gcr-prompter requested_mask=r denied_mask=r
ALLOWED gcr-prompter open /usr/share/mime/mime.cache comm=gcr-prompter requested_mask=r denied_mask=r
```

**Comment by roddhjav** [comment]
Thanks, this should be fixed now.
