### ISSUE TITLE
Nautilus trash showing error 

### ISSUE THREAD

**Issue by abhigit23** [roddhjav/apparmor.d#94]
After applying Apparmor profiles nautilus trash showed "This location couldn't be displayed."
Trashing files and folders are working fine but I can't access them through *Trash* tab.
I'm on Arch, installed profiles by following this repo's guide.
![image](https://user-images.githubusercontent.com/88484339/211833672-74050ee4-d6d3-48eb-878c-40a9a79e048f.png)

**Comment by roddhjav** [comment]
Can you provide with the result of `aa-log nautilus` (you might need sudo, depending of your setup)

**Comment by abhigit23** [comment]
> Can you provide the result of `aa-log nautilus` (you might need sudo, depending of your setup)

It returns nothing
I checked `aa-log` too but it has nothing related to nautilus
I tried to remove nautilus profile and then restart but still got the same error
Only disabling the Apparmor service works so far

**Comment by roddhjav** [comment]
Regardless of the AppArmor mode (complain or enforced) if AppArmor block something that will be present in the log (`/var/log/audit/audit.log`). Can you ensure you have [audit](https://wiki.archlinux.org/title/Audit_framework) installed and enabled?

**Comment by abhigit23** [comment]
> Regardless of the AppArmor mode (complain or enforced) if AppArmor block something that will be present in the log (`/var/log/audit/audit.log`). Can you ensure you have [audit](https://wiki.archlinux.org/title/Audit_framework) installed and enabled?

Yes, audit is installed, up and running.
![image](https://user-images.githubusercontent.com/88484339/212122019-494d0abc-e1a3-4231-832e-7fb45ba722ce.png)

This is `aa-log` output file
[aa-log.txt](https://github.com/roddhjav/apparmor.d/files/10403651/aa-log.txt)

**Comment by roddhjav** [comment]
Thanks. That help. It seems your audit log is getting a lot of stuff from AA. If they are different from the first one, can you also provide the result for `aa-log -f 1`, `aa-log -f 2`, `aa-log -f 3` and `aa-log -f 4`.

**Comment by abhigit23** [comment]
> Thanks. That help. It seems your audit log is getting a lot of stuff from AA. If they are different from the first one, can you also provide the result for `aa-log -f 1`, `aa-log -f 2`, `aa-log -f 3` and `aa-log -f 4`.

Thanks for the response.
I guess they are the same as the first one, anyway here are the output files:-
[aa-log -f 1.txt](https://github.com/roddhjav/apparmor.d/files/10404158/aa-log.-f.1.txt) | [aa-log -f 2.txt](https://github.com/roddhjav/apparmor.d/files/10404160/aa-log.-f.2.txt) | [aa-log -f 3.txt](https://github.com/roddhjav/apparmor.d/files/10404161/aa-log.-f.3.txt) | [aa-log -f 4.txt](https://github.com/roddhjav/apparmor.d/files/10404162/aa-log.-f.4.txt)

In addition to that error, I can't access my phone's storage(connected via USB) from nautilus showing this error, neither have access to the local FTP server.
![image](https://user-images.githubusercontent.com/88484339/212135301-49838766-c12d-48b5-90a7-57f4c336a1ff.png)

**Comment by nobody43** [comment]
@abhigit23 
I blame gvfs*. Try `/var/log/syslog`.

**Comment by abhigit23** [comment]
> @abhigit23 I blame gvfs*. Try `/var/log/syslog`.

bash: /var/log/syslog: No such file or directory
$ ls /var/log/
![image](https://user-images.githubusercontent.com/88484339/212143703-cc80f86d-8eb4-4de6-9a56-ed0e7261525b.png)

**Comment by nobody43** [comment]
`/var/log/lastlog` / `# dmesg`?

**Comment by abhigit23** [comment]
> `/var/log/lastlog` / `# dmesg`?

`/var/log/lastlog` returns nothing
`$ dmesg`  [dmesg.txt](https://github.com/roddhjav/apparmor.d/files/10404860/dmesg.txt)

Most errors are from audit `backlog limit exceeded` but nothing related to `gvfs`

**Comment by nobody43** [comment]
>Most errors are from audit "backlog limit exceeded" but nothing related to gvfs

Try searching on how to increase the limit, then:

`# dmesg | grep -i apparmor`

**Comment by roddhjav** [comment]
The issue with gvfs should be fixed now. So AA should complain far less. This will allow you to actually see the relevant error messages.

**Comment by abhigit23** [comment]
> > Most errors are from audit "backlog limit exceeded" but nothing related to gvfs
> 
> Try searching on how to increase the limit, then:
> 
> `# dmesg | grep -i apparmor`

Just two logs :-
![image](https://user-images.githubusercontent.com/88484339/212150167-ae27c421-a0f3-4e76-96d8-1b21a91e34e9.png)

**Comment by abhigit23** [comment]
I updated apparmor.d, audit not giving any *buffer space* errors now. Here are the logs :-

`$ sudo aa-log nautilus`

![image](https://user-images.githubusercontent.com/88484339/212377759-75bfb5d7-38af-45df-9418-a61a2d7f8854.png)

`$ sudo aa-log` 
[aa-log.txt](https://github.com/roddhjav/apparmor.d/files/10413771/aa-log.txt)

`$ sudo dmesg | grep -i apparmor`
[dmesg.txt](https://github.com/roddhjav/apparmor.d/files/10413803/dmesg.txt)

`$ journalctl -b | grep -i nautilus`
[journalctl.txt](https://github.com/roddhjav/apparmor.d/files/10413817/journalctl.txt)

**Comment by roddhjav** [comment]
Thanks a lot for these log. I will take care of them soon.

Regarding Nautilus, there is nothing here that would break the trash or the FTP client. Did you test them again after updating AppArmor.d?

**Comment by abhigit23** [comment]
Yes, I tested them again after updating AppArmor.d but still getting the same error, can't access trash and MTP unless I unload the profiles.
As for FTP :-

With AppArmor enabled and all profiles loaded nautilus showing this
![Profiles loaded](https://user-images.githubusercontent.com/88484339/212470840-a6ee76ac-9eb6-4420-863f-69df83e1640d.png)

After unloading profiles using `aa-teardown` command then logout and log back in, it let me connect
![Profiles unloaded](https://user-images.githubusercontent.com/88484339/212470951-45d1436a-bcbb-48d9-9a42-0809b7c23fb0.png)

**Comment by roddhjav** [comment]
That's weird, as there is nothing in the log that is related to those issues.

**Comment by vbauerster** [comment]
workaround to list trashed files:
```
gio trash --list
```

**Comment by jackb992** [comment]
After some trial and error, it seems (on my system anyway) that the nautilus trash error is caused by dbus-daemon, in particular line 47, changing @{lib} to @{libexec} allows access to trash again through nautilus. Although admittedly I do not understand how most of these profiles work, and found this through simple trial and error

**Comment by roddhjav** [comment]
You mean changing `@{libexec}` to `@{lib}`? libexec is not defined anymore.

**Comment by jackb992** [comment]
No lib to libexec, I did think it was weird since libexec wasn't defined, but removing line 47 still causes the error, but I guess putting an undefined variable doesn't???

**Comment by roddhjav** [comment]
You might still have the variable defined somewhere. Otherwise the profile would not compile.
Furthermore, `@{lib}` (instead of  `@{libexec}`) is a recent change, so it should have worked before?

**Comment by jackb992** [comment]
Yeah my bad taking a closer look at apparmor changing the variable stops that profile from loading, it must be something else in that dbus-daemon profile that's causing the error

**Comment by roddhjav** [comment]
I can now confirm, this is dbus that is causing the error (it works fine with dbus-broker without a profile). Just need to figure out the actual source cause of the issue.

**Comment by roddhjav** [comment]
For reference, this has been fixed a few months ago. This was related to #80
